### ISSUE TITLE
Create & Complete Presentation

### ISSUE THREAD

**Issue by d3li0n** [KentonMewling/Psych-Bot#1]
### Tasks to complete:

- [x] Create presentation slides. Tasked to @vinui409 @KentonMewling @RyanG418 
- [x] Record the video, edit, and submit. Tasked to @d3li0n 

Tasked to @KentonMewling 
- [x] Give a live demo of your project  (about  3-4  minutes).  
- [x] Highlight anything that works particularly well and anything particularly poorly. 
- [x] Give a brief overview of who did what (about 1 minute).
- [x] Show us the PM graphs of your project repository on GitHub (about 1 minute). 
- Graphs to show: the branching structure of the code, the commits per team member.
- [x] Show us the project management tool you use and the tickets you opened, assigned, and resolved.

**Comment by d3li0n** [comment]
In revision.
