### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by d3li0n** [KentonMewling/Psych-Bot#6]
Create a project plan and submit the document. The document is meant to help with upfront design, role assignment, task breakdown, and hours monitoring. Specifically, the report will include:

- [x] A brief description of your project (i.e., one paragraph), what you are doing, what role the agent and user take in a conversation. 
- The URL to your team repository should be included here.
- [x] Your chosen SDLC and rationale for its suitability (max. one paragraph). 
- [x] In point form: A listing of all the phases of the SDLC, where each phase should have at least **three** tasks. 
- Make sure at least two of the tasks have subtasks. 
- Give phases, tasks, and subtasks meaningful labels – run your labels by the Teaching Assistant; if you're not sure they are easy to understand by a third party.
- [x] A Work Breakdown Structure (WBS) showing task assigned to each team member, estimated duration of the task in hours (round to nearest half-hour), and actual duration of the task in hours (round to nearest half-hour). Provide a brief explanation of your WBS. 
- [x] A Gantt chart of your tasks, showing start and end dates for each task and showing dependencies across tasks. Provide a brief explanation of your chart.
- [x] Include tasks such as project meetings, planning documentation, WBS creation, code documentation, etc. 
- [x] Make a list of limitations of your program (e.g., it cannot handle synonyms, it cannot handle incorrect spelling, etc.)
- This list will serve as possible features for development in the next assignment.
- [x] Include sample output in your project report. Have one dialogue (at least 30 turns) that shows a good or feasible conversation. Have at least two short dialogues that show when your agent is not able to handle the conversation properly.

**Comment by d3li0n** [comment]
The issue is reviewed in Pull Request #23.

**Comment by d3li0n** [comment]
Resolved.
